version: '3.9'

services:
  app:
    build: .
    container_name: task_manager
    network_mode: host
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgres
    network_mode: host
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate
    network_mode: host
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://${DB_USERNAME}:${DB_PASSWORD}@localhost:5432/${DB_NAME}?sslmode=disable", "up" ]
    depends_on:
      - postgres

volumes:
  postgres_data: