version: '3.9'

services:
  app:
    build: .
    container_name: task_manager
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env
    networks:
      - application

  postgres:
    image: postgres:latest
    container_name: pg
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    volumes:
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -d ${DB_NAME}
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - application

  migrate:
    container_name: migrate
    image: migrate/migrate
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./schema
    command: [
      "-path", "/migrations", "-database",
      "postgres://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}?sslmode=disable", "up"
    ]
    networks:
      - application

networks:
  application:
    driver: bridge