name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./internal/... ./pkg/...

      - name: Generate Swagger
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -g internal/transport/rest/handler.go

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/serverfn:latest



      - name: Create .env file
        run: |
          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
          echo "DB_USERNAME=$DB_USERNAME" >> .env
          echo "DB_NAME=$DB_NAME" >> .env
      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Stop Docker Compose
        run: docker-compose down
